### PR TITLE
upgrade to use mysql cookbook version ~> 6.0

### PR DESCRIPTION
**Pull request by avsh**

### CODE REVIEW

**Comment by zuazo** [comment]
@avsh, thanks for the PR! LGTM :smiley:

Please, can you document the new attributes in the README and the metadata? The [usage](https://github.com/onddo/owncloud-cookbook#usage) section also needs to be updated.

**Comment by avsh** [comment]
@zuazo, I updated documented changes! Please, review

**Comment by zuazo** [comment]
Thanks @avsh. Give me a couple of days to test this carefully.

**Comment by zuazo** [comment]
Sorry for not having realized before, could you please move the `dbinstance`, `dbversion` and `dbrootpassword` to the `database` namespace? That's because the `config` namespace is used to populate the owncloud *config.php* configuration file.

I mean something like the following:

* `node['owncloud']['database']['instance']`
* `node['owncloud']['database']['version']`
* `node['owncloud']['database']['rootpassword']`

Thanks again for all your work :wink:

**Comment by avsh** [comment]
@zuazo, done

Tested against mysql, postgresql ubuntu 14.04

**Comment by zuazo** [comment]
@avsh, I'm going to merge this. Seems not to break anything. Thanks!

**Comment by zuazo** [comment]
Feature released in [1.0.0](https://github.com/zuazo/owncloud-cookbook/releases/tag/1.0.0).

**Pull request merged**
